name: UNIX Timestamp Converter
on: [push, pull_request]
jobs:
  gradle_runner:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Execute Gradle build
        run: gradle clean build -x test

      - name: Execute Gradle test
        run: gradle clean test

      - name: Execute Plugin Verifier
        run: gradle runPluginVerifier

      - name: Execute Sign Plugin
        run: gradle signPlugin
